
= Open API specification

== API info

open api version: 3.1.0

schema dialect: None

== Info

=== FicsIt Remote Monitoring

Document version: 1.0.10

Description: The JSON API provided by [Ficsit Remote Monitoring](https://ficsit.app/mod/FicsitRemoteMonitoring).

== Paths

=== /getFactory

==== get

_summary:_ Retrieve data on all factories in the world, regardless of type

_operation id:_ getFactory

.Responses

_200_

ref: <<_components_responses_GetFactory, #/components/responses/GetFactory>>

=== /getConstructor

==== get

_summary:_ Retrieve data on all constructors in the world

_operation id:_ getConstructor

.Responses

_200_

description: Successful operation

_Content_

.application/json

type: object

_Schema properties_

|===
|Property|Type
|*Name*|

ref: <<_components_schemas_BuildingName, #/components/schemas/BuildingName>>

|===

== Components

=== Schemas

==== BuildingName [[_components_schemas_BuildingName]]

type: string

description: The type of building

==== BuildingClassName [[_components_schemas_BuildingClassName]]

type: string

description: Unreal Engine class name of the building

==== LocationSingle [[_components_schemas_LocationSingle]]

type: object

_Schema properties_

|===
|Property|Type
|*x*|

type: number

format: double

description: Location on the world's X axis (east/west)

|*y*|

type: number

format: double

description: Location on the world's Y axis (north/south)

|*z*|

type: number

format: double

description: Location on the world's Z axis (up/down)

|*rotation*|

type: number

format: double

description: Rotation relative to the world with 0 as north

|===

=== Responses

==== GetFactory [[_components_responses_GetFactory]]

description: Successful operation

_Content_

.application/json

type: object

_Schema properties_

|===
|Property|Type
|*Name*|

ref: <<_components_schemas_BuildingName, #/components/schemas/BuildingName>>

|*ClassName*|

ref: <<_components_schemas_BuildingClassName, #/components/schemas/BuildingClassName>>

|*Location*|

ref: <<_components_schemas_LocationSingle, #/components/schemas/LocationSingle>>

|===

